// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               v7.35.0
// source: user.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import {
  type CallOptions,
  type ChannelCredentials,
  Client,
  type ClientOptions,
  type ClientReadableStream,
  type ClientUnaryCall,
  type ClientWritableStream,
  type handleClientStreamingCall,
  type handleServerStreamingCall,
  type handleUnaryCall,
  makeGenericClientConstructor,
  type Metadata,
  type ServiceError,
  type UntypedServiceImplementation,
} from "@grpc/grpc-js";

export const protobufPackage = "UserPackage";

export interface UserRequest {
  firstName: string;
  lastName: string;
  age: number;
  hobbies: string[];
  metadata: { [key: string]: string };
  middleName?: string | undefined;
  longServerId: number;
}

export interface UserRequest_MetadataEntry {
  key: string;
  value: string;
}

export interface UserResponse {
  msg: string;
}

export interface TargetUserRequest {
  firstName: string;
}

/** 1. Define a chunk message layout for tracking metric logs */
export interface WorkoutMetric {
  exerciseName: string;
  weightUsed: number;
}

function createBaseUserRequest(): UserRequest {
  return { firstName: "", lastName: "", age: 0, hobbies: [], metadata: {}, middleName: undefined, longServerId: 0 };
}

export const UserRequest: MessageFns<UserRequest> = {
  encode(message: UserRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.firstName !== "") {
      writer.uint32(10).string(message.firstName);
    }
    if (message.lastName !== "") {
      writer.uint32(18).string(message.lastName);
    }
    if (message.age !== 0) {
      writer.uint32(24).int32(message.age);
    }
    for (const v of message.hobbies) {
      writer.uint32(34).string(v!);
    }
    globalThis.Object.entries(message.metadata).forEach(([key, value]: [string, string]) => {
      UserRequest_MetadataEntry.encode({ key: key as any, value }, writer.uint32(42).fork()).join();
    });
    if (message.middleName !== undefined) {
      writer.uint32(50).string(message.middleName);
    }
    if (message.longServerId !== 0) {
      writer.uint32(56).int64(message.longServerId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): UserRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUserRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.firstName = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.lastName = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.age = reader.int32();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.hobbies.push(reader.string());
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          const entry5 = UserRequest_MetadataEntry.decode(reader, reader.uint32());
          if (entry5.value !== undefined) {
            message.metadata[entry5.key] = entry5.value;
          }
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.middleName = reader.string();
          continue;
        }
        case 7: {
          if (tag !== 56) {
            break;
          }

          message.longServerId = longToNumber(reader.int64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): UserRequest {
    return {
      firstName: isSet(object.firstName) ? globalThis.String(object.firstName) : "",
      lastName: isSet(object.lastName) ? globalThis.String(object.lastName) : "",
      age: isSet(object.age) ? globalThis.Number(object.age) : 0,
      hobbies: globalThis.Array.isArray(object?.hobbies) ? object.hobbies.map((e: any) => globalThis.String(e)) : [],
      metadata: isObject(object.metadata)
        ? (globalThis.Object.entries(object.metadata) as [string, any][]).reduce(
          (acc: { [key: string]: string }, [key, value]: [string, any]) => {
            acc[key] = globalThis.String(value);
            return acc;
          },
          {},
        )
        : {},
      middleName: isSet(object.middleName) ? globalThis.String(object.middleName) : undefined,
      longServerId: isSet(object.longServerId) ? globalThis.Number(object.longServerId) : 0,
    };
  },

  toJSON(message: UserRequest): unknown {
    const obj: any = {};
    if (message.firstName !== "") {
      obj.firstName = message.firstName;
    }
    if (message.lastName !== "") {
      obj.lastName = message.lastName;
    }
    if (message.age !== 0) {
      obj.age = Math.round(message.age);
    }
    if (message.hobbies?.length) {
      obj.hobbies = message.hobbies;
    }
    if (message.metadata) {
      const entries = globalThis.Object.entries(message.metadata) as [string, string][];
      if (entries.length > 0) {
        obj.metadata = {};
        entries.forEach(([k, v]) => {
          obj.metadata[k] = v;
        });
      }
    }
    if (message.middleName !== undefined) {
      obj.middleName = message.middleName;
    }
    if (message.longServerId !== 0) {
      obj.longServerId = Math.round(message.longServerId);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<UserRequest>, I>>(base?: I): UserRequest {
    return UserRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<UserRequest>, I>>(object: I): UserRequest {
    const message = createBaseUserRequest();
    message.firstName = object.firstName ?? "";
    message.lastName = object.lastName ?? "";
    message.age = object.age ?? 0;
    message.hobbies = object.hobbies?.map((e) => e) || [];
    message.metadata = (globalThis.Object.entries(object.metadata ?? {}) as [string, string][]).reduce(
      (acc: { [key: string]: string }, [key, value]: [string, string]) => {
        if (value !== undefined) {
          acc[key] = globalThis.String(value);
        }
        return acc;
      },
      {},
    );
    message.middleName = object.middleName ?? undefined;
    message.longServerId = object.longServerId ?? 0;
    return message;
  },
};

function createBaseUserRequest_MetadataEntry(): UserRequest_MetadataEntry {
  return { key: "", value: "" };
}

export const UserRequest_MetadataEntry: MessageFns<UserRequest_MetadataEntry> = {
  encode(message: UserRequest_MetadataEntry, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.key !== "") {
      writer.uint32(10).string(message.key);
    }
    if (message.value !== "") {
      writer.uint32(18).string(message.value);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): UserRequest_MetadataEntry {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUserRequest_MetadataEntry();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.key = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.value = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): UserRequest_MetadataEntry {
    return {
      key: isSet(object.key) ? globalThis.String(object.key) : "",
      value: isSet(object.value) ? globalThis.String(object.value) : "",
    };
  },

  toJSON(message: UserRequest_MetadataEntry): unknown {
    const obj: any = {};
    if (message.key !== "") {
      obj.key = message.key;
    }
    if (message.value !== "") {
      obj.value = message.value;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<UserRequest_MetadataEntry>, I>>(base?: I): UserRequest_MetadataEntry {
    return UserRequest_MetadataEntry.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<UserRequest_MetadataEntry>, I>>(object: I): UserRequest_MetadataEntry {
    const message = createBaseUserRequest_MetadataEntry();
    message.key = object.key ?? "";
    message.value = object.value ?? "";
    return message;
  },
};

function createBaseUserResponse(): UserResponse {
  return { msg: "" };
}

export const UserResponse: MessageFns<UserResponse> = {
  encode(message: UserResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.msg !== "") {
      writer.uint32(10).string(message.msg);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): UserResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUserResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.msg = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): UserResponse {
    return { msg: isSet(object.msg) ? globalThis.String(object.msg) : "" };
  },

  toJSON(message: UserResponse): unknown {
    const obj: any = {};
    if (message.msg !== "") {
      obj.msg = message.msg;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<UserResponse>, I>>(base?: I): UserResponse {
    return UserResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<UserResponse>, I>>(object: I): UserResponse {
    const message = createBaseUserResponse();
    message.msg = object.msg ?? "";
    return message;
  },
};

function createBaseTargetUserRequest(): TargetUserRequest {
  return { firstName: "" };
}

export const TargetUserRequest: MessageFns<TargetUserRequest> = {
  encode(message: TargetUserRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.firstName !== "") {
      writer.uint32(10).string(message.firstName);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): TargetUserRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseTargetUserRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.firstName = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): TargetUserRequest {
    return { firstName: isSet(object.firstName) ? globalThis.String(object.firstName) : "" };
  },

  toJSON(message: TargetUserRequest): unknown {
    const obj: any = {};
    if (message.firstName !== "") {
      obj.firstName = message.firstName;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<TargetUserRequest>, I>>(base?: I): TargetUserRequest {
    return TargetUserRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<TargetUserRequest>, I>>(object: I): TargetUserRequest {
    const message = createBaseTargetUserRequest();
    message.firstName = object.firstName ?? "";
    return message;
  },
};

function createBaseWorkoutMetric(): WorkoutMetric {
  return { exerciseName: "", weightUsed: 0 };
}

export const WorkoutMetric: MessageFns<WorkoutMetric> = {
  encode(message: WorkoutMetric, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.exerciseName !== "") {
      writer.uint32(10).string(message.exerciseName);
    }
    if (message.weightUsed !== 0) {
      writer.uint32(16).int32(message.weightUsed);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): WorkoutMetric {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseWorkoutMetric();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.exerciseName = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.weightUsed = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): WorkoutMetric {
    return {
      exerciseName: isSet(object.exerciseName) ? globalThis.String(object.exerciseName) : "",
      weightUsed: isSet(object.weightUsed) ? globalThis.Number(object.weightUsed) : 0,
    };
  },

  toJSON(message: WorkoutMetric): unknown {
    const obj: any = {};
    if (message.exerciseName !== "") {
      obj.exerciseName = message.exerciseName;
    }
    if (message.weightUsed !== 0) {
      obj.weightUsed = Math.round(message.weightUsed);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<WorkoutMetric>, I>>(base?: I): WorkoutMetric {
    return WorkoutMetric.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<WorkoutMetric>, I>>(object: I): WorkoutMetric {
    const message = createBaseWorkoutMetric();
    message.exerciseName = object.exerciseName ?? "";
    message.weightUsed = object.weightUsed ?? 0;
    return message;
  },
};

export type UserServiceService = typeof UserServiceService;
export const UserServiceService = {
  createUser: {
    path: "/UserPackage.UserService/CreateUser" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: UserRequest): Buffer => Buffer.from(UserRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): UserRequest => UserRequest.decode(value),
    responseSerialize: (value: UserResponse): Buffer => Buffer.from(UserResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): UserResponse => UserResponse.decode(value),
  },
  streamUserActivities: {
    path: "/UserPackage.UserService/StreamUserActivities" as const,
    requestStream: false as const,
    responseStream: true as const,
    requestSerialize: (value: TargetUserRequest): Buffer => Buffer.from(TargetUserRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): TargetUserRequest => TargetUserRequest.decode(value),
    responseSerialize: (value: UserResponse): Buffer => Buffer.from(UserResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): UserResponse => UserResponse.decode(value),
  },
  /** 2. The 'stream' keyword here tells gRPC that the client pushes a continuous stream */
  recordWorkoutSession: {
    path: "/UserPackage.UserService/RecordWorkoutSession" as const,
    requestStream: true as const,
    responseStream: false as const,
    requestSerialize: (value: WorkoutMetric): Buffer => Buffer.from(WorkoutMetric.encode(value).finish()),
    requestDeserialize: (value: Buffer): WorkoutMetric => WorkoutMetric.decode(value),
    responseSerialize: (value: UserResponse): Buffer => Buffer.from(UserResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): UserResponse => UserResponse.decode(value),
  },
} as const;

export interface UserServiceServer extends UntypedServiceImplementation {
  createUser: handleUnaryCall<UserRequest, UserResponse>;
  streamUserActivities: handleServerStreamingCall<TargetUserRequest, UserResponse>;
  /** 2. The 'stream' keyword here tells gRPC that the client pushes a continuous stream */
  recordWorkoutSession: handleClientStreamingCall<WorkoutMetric, UserResponse>;
}

export interface UserServiceClient extends Client {
  createUser(
    request: UserRequest,
    callback: (error: ServiceError | null, response: UserResponse) => void,
  ): ClientUnaryCall;
  createUser(
    request: UserRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: UserResponse) => void,
  ): ClientUnaryCall;
  createUser(
    request: UserRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: UserResponse) => void,
  ): ClientUnaryCall;
  streamUserActivities(request: TargetUserRequest, options?: Partial<CallOptions>): ClientReadableStream<UserResponse>;
  streamUserActivities(
    request: TargetUserRequest,
    metadata?: Metadata,
    options?: Partial<CallOptions>,
  ): ClientReadableStream<UserResponse>;
  /** 2. The 'stream' keyword here tells gRPC that the client pushes a continuous stream */
  recordWorkoutSession(
    callback: (error: ServiceError | null, response: UserResponse) => void,
  ): ClientWritableStream<WorkoutMetric>;
  recordWorkoutSession(
    metadata: Metadata,
    callback: (error: ServiceError | null, response: UserResponse) => void,
  ): ClientWritableStream<WorkoutMetric>;
  recordWorkoutSession(
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: UserResponse) => void,
  ): ClientWritableStream<WorkoutMetric>;
  recordWorkoutSession(
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: UserResponse) => void,
  ): ClientWritableStream<WorkoutMetric>;
}

export const UserServiceClient = makeGenericClientConstructor(
  UserServiceService,
  "UserPackage.UserService",
) as unknown as {
  new (address: string, credentials: ChannelCredentials, options?: Partial<ClientOptions>): UserServiceClient;
  service: typeof UserServiceService;
  serviceName: string;
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

function isObject(value: any): boolean {
  return typeof value === "object" && value !== null;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
