// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               v7.35.0
// source: user.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import {
  type CallOptions,
  type ChannelCredentials,
  Client,
  type ClientOptions,
  type ClientUnaryCall,
  type handleUnaryCall,
  makeGenericClientConstructor,
  type Metadata,
  type ServiceError,
  type UntypedServiceImplementation,
} from "@grpc/grpc-js";

export const protobufPackage = "UserPackage";

export interface LoggedRequest {
  payload: string;
}

export interface LoggedResponse {
  result: string;
}

function createBaseLoggedRequest(): LoggedRequest {
  return { payload: "" };
}

export const LoggedRequest: MessageFns<LoggedRequest> = {
  encode(message: LoggedRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.payload !== "") {
      writer.uint32(10).string(message.payload);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): LoggedRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseLoggedRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.payload = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): LoggedRequest {
    return { payload: isSet(object.payload) ? globalThis.String(object.payload) : "" };
  },

  toJSON(message: LoggedRequest): unknown {
    const obj: any = {};
    if (message.payload !== "") {
      obj.payload = message.payload;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<LoggedRequest>, I>>(base?: I): LoggedRequest {
    return LoggedRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<LoggedRequest>, I>>(object: I): LoggedRequest {
    const message = createBaseLoggedRequest();
    message.payload = object.payload ?? "";
    return message;
  },
};

function createBaseLoggedResponse(): LoggedResponse {
  return { result: "" };
}

export const LoggedResponse: MessageFns<LoggedResponse> = {
  encode(message: LoggedResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.result !== "") {
      writer.uint32(10).string(message.result);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): LoggedResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseLoggedResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.result = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): LoggedResponse {
    return { result: isSet(object.result) ? globalThis.String(object.result) : "" };
  },

  toJSON(message: LoggedResponse): unknown {
    const obj: any = {};
    if (message.result !== "") {
      obj.result = message.result;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<LoggedResponse>, I>>(base?: I): LoggedResponse {
    return LoggedResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<LoggedResponse>, I>>(object: I): LoggedResponse {
    const message = createBaseLoggedResponse();
    message.result = object.result ?? "";
    return message;
  },
};

export type UserServiceService = typeof UserServiceService;
export const UserServiceService = {
  executeTask: {
    path: "/UserPackage.UserService/ExecuteTask" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: LoggedRequest): Buffer => Buffer.from(LoggedRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): LoggedRequest => LoggedRequest.decode(value),
    responseSerialize: (value: LoggedResponse): Buffer => Buffer.from(LoggedResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): LoggedResponse => LoggedResponse.decode(value),
  },
} as const;

export interface UserServiceServer extends UntypedServiceImplementation {
  executeTask: handleUnaryCall<LoggedRequest, LoggedResponse>;
}

export interface UserServiceClient extends Client {
  executeTask(
    request: LoggedRequest,
    callback: (error: ServiceError | null, response: LoggedResponse) => void,
  ): ClientUnaryCall;
  executeTask(
    request: LoggedRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: LoggedResponse) => void,
  ): ClientUnaryCall;
  executeTask(
    request: LoggedRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: LoggedResponse) => void,
  ): ClientUnaryCall;
}

export const UserServiceClient = makeGenericClientConstructor(
  UserServiceService,
  "UserPackage.UserService",
) as unknown as {
  new (address: string, credentials: ChannelCredentials, options?: Partial<ClientOptions>): UserServiceClient;
  service: typeof UserServiceService;
  serviceName: string;
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
