// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               v7.35.0
// source: user.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import {
  type CallOptions,
  type ChannelCredentials,
  Client,
  type ClientOptions,
  type ClientUnaryCall,
  type handleUnaryCall,
  makeGenericClientConstructor,
  type Metadata,
  type ServiceError,
  type UntypedServiceImplementation,
} from "@grpc/grpc-js";

export const protobufPackage = "UserPackage";

export interface WorkoutRequest {
  workoutId: string;
}

export interface WorkoutResponse {
  title: string;
  targetSets: number;
}

function createBaseWorkoutRequest(): WorkoutRequest {
  return { workoutId: "" };
}

export const WorkoutRequest: MessageFns<WorkoutRequest> = {
  encode(message: WorkoutRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.workoutId !== "") {
      writer.uint32(10).string(message.workoutId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): WorkoutRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseWorkoutRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.workoutId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): WorkoutRequest {
    return { workoutId: isSet(object.workoutId) ? globalThis.String(object.workoutId) : "" };
  },

  toJSON(message: WorkoutRequest): unknown {
    const obj: any = {};
    if (message.workoutId !== "") {
      obj.workoutId = message.workoutId;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<WorkoutRequest>, I>>(base?: I): WorkoutRequest {
    return WorkoutRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<WorkoutRequest>, I>>(object: I): WorkoutRequest {
    const message = createBaseWorkoutRequest();
    message.workoutId = object.workoutId ?? "";
    return message;
  },
};

function createBaseWorkoutResponse(): WorkoutResponse {
  return { title: "", targetSets: 0 };
}

export const WorkoutResponse: MessageFns<WorkoutResponse> = {
  encode(message: WorkoutResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.title !== "") {
      writer.uint32(10).string(message.title);
    }
    if (message.targetSets !== 0) {
      writer.uint32(16).int32(message.targetSets);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): WorkoutResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseWorkoutResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.title = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.targetSets = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): WorkoutResponse {
    return {
      title: isSet(object.title) ? globalThis.String(object.title) : "",
      targetSets: isSet(object.targetSets) ? globalThis.Number(object.targetSets) : 0,
    };
  },

  toJSON(message: WorkoutResponse): unknown {
    const obj: any = {};
    if (message.title !== "") {
      obj.title = message.title;
    }
    if (message.targetSets !== 0) {
      obj.targetSets = Math.round(message.targetSets);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<WorkoutResponse>, I>>(base?: I): WorkoutResponse {
    return WorkoutResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<WorkoutResponse>, I>>(object: I): WorkoutResponse {
    const message = createBaseWorkoutResponse();
    message.title = object.title ?? "";
    message.targetSets = object.targetSets ?? 0;
    return message;
  },
};

export type UserServiceService = typeof UserServiceService;
export const UserServiceService = {
  getWorkoutDetails: {
    path: "/UserPackage.UserService/GetWorkoutDetails" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: WorkoutRequest): Buffer => Buffer.from(WorkoutRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): WorkoutRequest => WorkoutRequest.decode(value),
    responseSerialize: (value: WorkoutResponse): Buffer => Buffer.from(WorkoutResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): WorkoutResponse => WorkoutResponse.decode(value),
  },
} as const;

export interface UserServiceServer extends UntypedServiceImplementation {
  getWorkoutDetails: handleUnaryCall<WorkoutRequest, WorkoutResponse>;
}

export interface UserServiceClient extends Client {
  getWorkoutDetails(
    request: WorkoutRequest,
    callback: (error: ServiceError | null, response: WorkoutResponse) => void,
  ): ClientUnaryCall;
  getWorkoutDetails(
    request: WorkoutRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: WorkoutResponse) => void,
  ): ClientUnaryCall;
  getWorkoutDetails(
    request: WorkoutRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: WorkoutResponse) => void,
  ): ClientUnaryCall;
}

export const UserServiceClient = makeGenericClientConstructor(
  UserServiceService,
  "UserPackage.UserService",
) as unknown as {
  new (address: string, credentials: ChannelCredentials, options?: Partial<ClientOptions>): UserServiceClient;
  service: typeof UserServiceService;
  serviceName: string;
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
