// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               v7.35.0
// source: user.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import {
  type CallOptions,
  type ChannelCredentials,
  Client,
  type ClientOptions,
  type ClientUnaryCall,
  type handleUnaryCall,
  makeGenericClientConstructor,
  type Metadata,
  type ServiceError,
  type UntypedServiceImplementation,
} from "@grpc/grpc-js";

export const protobufPackage = "MasterPackage";

/** 1. Enum Definition */
export enum AccountStatus {
  /** STATUS_UNKNOWN - proto3 requires the first element to map to 0 */
  STATUS_UNKNOWN = 0,
  STATUS_ACTIVE = 1,
  STATUS_SUSPENDED = 2,
  STATUS_BANNED = 3,
  UNRECOGNIZED = -1,
}

export function accountStatusFromJSON(object: any): AccountStatus {
  switch (object) {
    case 0:
    case "STATUS_UNKNOWN":
      return AccountStatus.STATUS_UNKNOWN;
    case 1:
    case "STATUS_ACTIVE":
      return AccountStatus.STATUS_ACTIVE;
    case 2:
    case "STATUS_SUSPENDED":
      return AccountStatus.STATUS_SUSPENDED;
    case 3:
    case "STATUS_BANNED":
      return AccountStatus.STATUS_BANNED;
    case -1:
    case "UNRECOGNIZED":
    default:
      return AccountStatus.UNRECOGNIZED;
  }
}

export function accountStatusToJSON(object: AccountStatus): string {
  switch (object) {
    case AccountStatus.STATUS_UNKNOWN:
      return "STATUS_UNKNOWN";
    case AccountStatus.STATUS_ACTIVE:
      return "STATUS_ACTIVE";
    case AccountStatus.STATUS_SUSPENDED:
      return "STATUS_SUSPENDED";
    case AccountStatus.STATUS_BANNED:
      return "STATUS_BANNED";
    case AccountStatus.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

/** 2. Child Message for nesting references */
export interface SubProfile {
  bio: string;
  avatarUrl: string;
}

/** 3. The Master Payload encompassing all type families */
export interface ComprehensiveDataRequest {
  /** --- Text & Binary Types --- */
  textString: string;
  /** Maps to Uint8Array in TypeScript */
  rawBinaryData: Uint8Array;
  /** --- Boolean Type --- */
  isPremiumUser: boolean;
  /** --- Floating-Point Types --- */
  singlePrecisionFloat: number;
  /** 64-bit floating point */
  doublePrecisionFloat: number;
  /** --- Standard Signed Integer Types (Variable-length encoding) --- */
  standardInt32: number;
  /** Maps to Long or string/number depending on compiler */
  standardInt64: number;
  /** --- Unsigned Integer Types (Variable-length encoding) --- */
  unsignedInt32: number;
  unsignedInt64: number;
  /** --- Signed Integers with Efficient Negative Encoding (ZigZag encoding) --- */
  signedZigZagInt32: number;
  signedZigZagInt64: number;
  /** --- Fixed-Length Integers (Always takes 4 or 8 bytes respectively) --- */
  fixedLengthInt32: number;
  fixedLengthInt64: number;
  signedFixedLengthInt32: number;
  signedFixedLengthInt64: number;
  /** --- Complex Collection Fields --- */
  tagList: string[];
  /** Key-Value Dictionary map */
  configurationMap: { [key: string]: string };
  /** --- Structuring & References --- */
  currentStatus: AccountStatus;
  /** Embedded Sub-Message Object */
  nestedProfile:
    | SubProfile
    | undefined;
  /** --- Explicit Modifiers & Polymorphism --- */
  conditionalNickname?: string | undefined;
  passportNumber?: string | undefined;
  nationalIdNumber?: string | undefined;
}

export interface ComprehensiveDataRequest_ConfigurationMapEntry {
  key: string;
  value: string;
}

export interface MasterResponse {
  processingSuccess: boolean;
  summaryLog: string;
}

function createBaseSubProfile(): SubProfile {
  return { bio: "", avatarUrl: "" };
}

export const SubProfile: MessageFns<SubProfile> = {
  encode(message: SubProfile, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.bio !== "") {
      writer.uint32(10).string(message.bio);
    }
    if (message.avatarUrl !== "") {
      writer.uint32(18).string(message.avatarUrl);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SubProfile {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSubProfile();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.bio = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.avatarUrl = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SubProfile {
    return {
      bio: isSet(object.bio) ? globalThis.String(object.bio) : "",
      avatarUrl: isSet(object.avatarUrl) ? globalThis.String(object.avatarUrl) : "",
    };
  },

  toJSON(message: SubProfile): unknown {
    const obj: any = {};
    if (message.bio !== "") {
      obj.bio = message.bio;
    }
    if (message.avatarUrl !== "") {
      obj.avatarUrl = message.avatarUrl;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SubProfile>, I>>(base?: I): SubProfile {
    return SubProfile.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SubProfile>, I>>(object: I): SubProfile {
    const message = createBaseSubProfile();
    message.bio = object.bio ?? "";
    message.avatarUrl = object.avatarUrl ?? "";
    return message;
  },
};

function createBaseComprehensiveDataRequest(): ComprehensiveDataRequest {
  return {
    textString: "",
    rawBinaryData: new Uint8Array(0),
    isPremiumUser: false,
    singlePrecisionFloat: 0,
    doublePrecisionFloat: 0,
    standardInt32: 0,
    standardInt64: 0,
    unsignedInt32: 0,
    unsignedInt64: 0,
    signedZigZagInt32: 0,
    signedZigZagInt64: 0,
    fixedLengthInt32: 0,
    fixedLengthInt64: 0,
    signedFixedLengthInt32: 0,
    signedFixedLengthInt64: 0,
    tagList: [],
    configurationMap: {},
    currentStatus: 0,
    nestedProfile: undefined,
    conditionalNickname: undefined,
    passportNumber: undefined,
    nationalIdNumber: undefined,
  };
}

export const ComprehensiveDataRequest: MessageFns<ComprehensiveDataRequest> = {
  encode(message: ComprehensiveDataRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.textString !== "") {
      writer.uint32(10).string(message.textString);
    }
    if (message.rawBinaryData.length !== 0) {
      writer.uint32(18).bytes(message.rawBinaryData);
    }
    if (message.isPremiumUser !== false) {
      writer.uint32(24).bool(message.isPremiumUser);
    }
    if (message.singlePrecisionFloat !== 0) {
      writer.uint32(37).float(message.singlePrecisionFloat);
    }
    if (message.doublePrecisionFloat !== 0) {
      writer.uint32(41).double(message.doublePrecisionFloat);
    }
    if (message.standardInt32 !== 0) {
      writer.uint32(48).int32(message.standardInt32);
    }
    if (message.standardInt64 !== 0) {
      writer.uint32(56).int64(message.standardInt64);
    }
    if (message.unsignedInt32 !== 0) {
      writer.uint32(64).uint32(message.unsignedInt32);
    }
    if (message.unsignedInt64 !== 0) {
      writer.uint32(72).uint64(message.unsignedInt64);
    }
    if (message.signedZigZagInt32 !== 0) {
      writer.uint32(80).sint32(message.signedZigZagInt32);
    }
    if (message.signedZigZagInt64 !== 0) {
      writer.uint32(88).sint64(message.signedZigZagInt64);
    }
    if (message.fixedLengthInt32 !== 0) {
      writer.uint32(101).fixed32(message.fixedLengthInt32);
    }
    if (message.fixedLengthInt64 !== 0) {
      writer.uint32(105).fixed64(message.fixedLengthInt64);
    }
    if (message.signedFixedLengthInt32 !== 0) {
      writer.uint32(117).sfixed32(message.signedFixedLengthInt32);
    }
    if (message.signedFixedLengthInt64 !== 0) {
      writer.uint32(121).sfixed64(message.signedFixedLengthInt64);
    }
    for (const v of message.tagList) {
      writer.uint32(130).string(v!);
    }
    globalThis.Object.entries(message.configurationMap).forEach(([key, value]: [string, string]) => {
      ComprehensiveDataRequest_ConfigurationMapEntry.encode({ key: key as any, value }, writer.uint32(138).fork())
        .join();
    });
    if (message.currentStatus !== 0) {
      writer.uint32(144).int32(message.currentStatus);
    }
    if (message.nestedProfile !== undefined) {
      SubProfile.encode(message.nestedProfile, writer.uint32(154).fork()).join();
    }
    if (message.conditionalNickname !== undefined) {
      writer.uint32(162).string(message.conditionalNickname);
    }
    if (message.passportNumber !== undefined) {
      writer.uint32(170).string(message.passportNumber);
    }
    if (message.nationalIdNumber !== undefined) {
      writer.uint32(178).string(message.nationalIdNumber);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ComprehensiveDataRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseComprehensiveDataRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.textString = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.rawBinaryData = reader.bytes();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.isPremiumUser = reader.bool();
          continue;
        }
        case 4: {
          if (tag !== 37) {
            break;
          }

          message.singlePrecisionFloat = reader.float();
          continue;
        }
        case 5: {
          if (tag !== 41) {
            break;
          }

          message.doublePrecisionFloat = reader.double();
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.standardInt32 = reader.int32();
          continue;
        }
        case 7: {
          if (tag !== 56) {
            break;
          }

          message.standardInt64 = longToNumber(reader.int64());
          continue;
        }
        case 8: {
          if (tag !== 64) {
            break;
          }

          message.unsignedInt32 = reader.uint32();
          continue;
        }
        case 9: {
          if (tag !== 72) {
            break;
          }

          message.unsignedInt64 = longToNumber(reader.uint64());
          continue;
        }
        case 10: {
          if (tag !== 80) {
            break;
          }

          message.signedZigZagInt32 = reader.sint32();
          continue;
        }
        case 11: {
          if (tag !== 88) {
            break;
          }

          message.signedZigZagInt64 = longToNumber(reader.sint64());
          continue;
        }
        case 12: {
          if (tag !== 101) {
            break;
          }

          message.fixedLengthInt32 = reader.fixed32();
          continue;
        }
        case 13: {
          if (tag !== 105) {
            break;
          }

          message.fixedLengthInt64 = longToNumber(reader.fixed64());
          continue;
        }
        case 14: {
          if (tag !== 117) {
            break;
          }

          message.signedFixedLengthInt32 = reader.sfixed32();
          continue;
        }
        case 15: {
          if (tag !== 121) {
            break;
          }

          message.signedFixedLengthInt64 = longToNumber(reader.sfixed64());
          continue;
        }
        case 16: {
          if (tag !== 130) {
            break;
          }

          message.tagList.push(reader.string());
          continue;
        }
        case 17: {
          if (tag !== 138) {
            break;
          }

          const entry17 = ComprehensiveDataRequest_ConfigurationMapEntry.decode(reader, reader.uint32());
          if (entry17.value !== undefined) {
            message.configurationMap[entry17.key] = entry17.value;
          }
          continue;
        }
        case 18: {
          if (tag !== 144) {
            break;
          }

          message.currentStatus = reader.int32() as any;
          continue;
        }
        case 19: {
          if (tag !== 154) {
            break;
          }

          message.nestedProfile = SubProfile.decode(reader, reader.uint32());
          continue;
        }
        case 20: {
          if (tag !== 162) {
            break;
          }

          message.conditionalNickname = reader.string();
          continue;
        }
        case 21: {
          if (tag !== 170) {
            break;
          }

          message.passportNumber = reader.string();
          continue;
        }
        case 22: {
          if (tag !== 178) {
            break;
          }

          message.nationalIdNumber = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ComprehensiveDataRequest {
    return {
      textString: isSet(object.textString) ? globalThis.String(object.textString) : "",
      rawBinaryData: isSet(object.rawBinaryData) ? bytesFromBase64(object.rawBinaryData) : new Uint8Array(0),
      isPremiumUser: isSet(object.isPremiumUser) ? globalThis.Boolean(object.isPremiumUser) : false,
      singlePrecisionFloat: isSet(object.singlePrecisionFloat) ? globalThis.Number(object.singlePrecisionFloat) : 0,
      doublePrecisionFloat: isSet(object.doublePrecisionFloat) ? globalThis.Number(object.doublePrecisionFloat) : 0,
      standardInt32: isSet(object.standardInt32) ? globalThis.Number(object.standardInt32) : 0,
      standardInt64: isSet(object.standardInt64) ? globalThis.Number(object.standardInt64) : 0,
      unsignedInt32: isSet(object.unsignedInt32) ? globalThis.Number(object.unsignedInt32) : 0,
      unsignedInt64: isSet(object.unsignedInt64) ? globalThis.Number(object.unsignedInt64) : 0,
      signedZigZagInt32: isSet(object.signedZigZagInt32) ? globalThis.Number(object.signedZigZagInt32) : 0,
      signedZigZagInt64: isSet(object.signedZigZagInt64) ? globalThis.Number(object.signedZigZagInt64) : 0,
      fixedLengthInt32: isSet(object.fixedLengthInt32) ? globalThis.Number(object.fixedLengthInt32) : 0,
      fixedLengthInt64: isSet(object.fixedLengthInt64) ? globalThis.Number(object.fixedLengthInt64) : 0,
      signedFixedLengthInt32: isSet(object.signedFixedLengthInt32)
        ? globalThis.Number(object.signedFixedLengthInt32)
        : 0,
      signedFixedLengthInt64: isSet(object.signedFixedLengthInt64)
        ? globalThis.Number(object.signedFixedLengthInt64)
        : 0,
      tagList: globalThis.Array.isArray(object?.tagList) ? object.tagList.map((e: any) => globalThis.String(e)) : [],
      configurationMap: isObject(object.configurationMap)
        ? (globalThis.Object.entries(object.configurationMap) as [string, any][]).reduce(
          (acc: { [key: string]: string }, [key, value]: [string, any]) => {
            acc[key] = globalThis.String(value);
            return acc;
          },
          {},
        )
        : {},
      currentStatus: isSet(object.currentStatus) ? accountStatusFromJSON(object.currentStatus) : 0,
      nestedProfile: isSet(object.nestedProfile) ? SubProfile.fromJSON(object.nestedProfile) : undefined,
      conditionalNickname: isSet(object.conditionalNickname)
        ? globalThis.String(object.conditionalNickname)
        : undefined,
      passportNumber: isSet(object.passportNumber) ? globalThis.String(object.passportNumber) : undefined,
      nationalIdNumber: isSet(object.nationalIdNumber) ? globalThis.String(object.nationalIdNumber) : undefined,
    };
  },

  toJSON(message: ComprehensiveDataRequest): unknown {
    const obj: any = {};
    if (message.textString !== "") {
      obj.textString = message.textString;
    }
    if (message.rawBinaryData.length !== 0) {
      obj.rawBinaryData = base64FromBytes(message.rawBinaryData);
    }
    if (message.isPremiumUser !== false) {
      obj.isPremiumUser = message.isPremiumUser;
    }
    if (message.singlePrecisionFloat !== 0) {
      obj.singlePrecisionFloat = message.singlePrecisionFloat;
    }
    if (message.doublePrecisionFloat !== 0) {
      obj.doublePrecisionFloat = message.doublePrecisionFloat;
    }
    if (message.standardInt32 !== 0) {
      obj.standardInt32 = Math.round(message.standardInt32);
    }
    if (message.standardInt64 !== 0) {
      obj.standardInt64 = Math.round(message.standardInt64);
    }
    if (message.unsignedInt32 !== 0) {
      obj.unsignedInt32 = Math.round(message.unsignedInt32);
    }
    if (message.unsignedInt64 !== 0) {
      obj.unsignedInt64 = Math.round(message.unsignedInt64);
    }
    if (message.signedZigZagInt32 !== 0) {
      obj.signedZigZagInt32 = Math.round(message.signedZigZagInt32);
    }
    if (message.signedZigZagInt64 !== 0) {
      obj.signedZigZagInt64 = Math.round(message.signedZigZagInt64);
    }
    if (message.fixedLengthInt32 !== 0) {
      obj.fixedLengthInt32 = Math.round(message.fixedLengthInt32);
    }
    if (message.fixedLengthInt64 !== 0) {
      obj.fixedLengthInt64 = Math.round(message.fixedLengthInt64);
    }
    if (message.signedFixedLengthInt32 !== 0) {
      obj.signedFixedLengthInt32 = Math.round(message.signedFixedLengthInt32);
    }
    if (message.signedFixedLengthInt64 !== 0) {
      obj.signedFixedLengthInt64 = Math.round(message.signedFixedLengthInt64);
    }
    if (message.tagList?.length) {
      obj.tagList = message.tagList;
    }
    if (message.configurationMap) {
      const entries = globalThis.Object.entries(message.configurationMap) as [string, string][];
      if (entries.length > 0) {
        obj.configurationMap = {};
        entries.forEach(([k, v]) => {
          obj.configurationMap[k] = v;
        });
      }
    }
    if (message.currentStatus !== 0) {
      obj.currentStatus = accountStatusToJSON(message.currentStatus);
    }
    if (message.nestedProfile !== undefined) {
      obj.nestedProfile = SubProfile.toJSON(message.nestedProfile);
    }
    if (message.conditionalNickname !== undefined) {
      obj.conditionalNickname = message.conditionalNickname;
    }
    if (message.passportNumber !== undefined) {
      obj.passportNumber = message.passportNumber;
    }
    if (message.nationalIdNumber !== undefined) {
      obj.nationalIdNumber = message.nationalIdNumber;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ComprehensiveDataRequest>, I>>(base?: I): ComprehensiveDataRequest {
    return ComprehensiveDataRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ComprehensiveDataRequest>, I>>(object: I): ComprehensiveDataRequest {
    const message = createBaseComprehensiveDataRequest();
    message.textString = object.textString ?? "";
    message.rawBinaryData = object.rawBinaryData ?? new Uint8Array(0);
    message.isPremiumUser = object.isPremiumUser ?? false;
    message.singlePrecisionFloat = object.singlePrecisionFloat ?? 0;
    message.doublePrecisionFloat = object.doublePrecisionFloat ?? 0;
    message.standardInt32 = object.standardInt32 ?? 0;
    message.standardInt64 = object.standardInt64 ?? 0;
    message.unsignedInt32 = object.unsignedInt32 ?? 0;
    message.unsignedInt64 = object.unsignedInt64 ?? 0;
    message.signedZigZagInt32 = object.signedZigZagInt32 ?? 0;
    message.signedZigZagInt64 = object.signedZigZagInt64 ?? 0;
    message.fixedLengthInt32 = object.fixedLengthInt32 ?? 0;
    message.fixedLengthInt64 = object.fixedLengthInt64 ?? 0;
    message.signedFixedLengthInt32 = object.signedFixedLengthInt32 ?? 0;
    message.signedFixedLengthInt64 = object.signedFixedLengthInt64 ?? 0;
    message.tagList = object.tagList?.map((e) => e) || [];
    message.configurationMap = (globalThis.Object.entries(object.configurationMap ?? {}) as [string, string][]).reduce(
      (acc: { [key: string]: string }, [key, value]: [string, string]) => {
        if (value !== undefined) {
          acc[key] = globalThis.String(value);
        }
        return acc;
      },
      {},
    );
    message.currentStatus = object.currentStatus ?? 0;
    message.nestedProfile = (object.nestedProfile !== undefined && object.nestedProfile !== null)
      ? SubProfile.fromPartial(object.nestedProfile)
      : undefined;
    message.conditionalNickname = object.conditionalNickname ?? undefined;
    message.passportNumber = object.passportNumber ?? undefined;
    message.nationalIdNumber = object.nationalIdNumber ?? undefined;
    return message;
  },
};

function createBaseComprehensiveDataRequest_ConfigurationMapEntry(): ComprehensiveDataRequest_ConfigurationMapEntry {
  return { key: "", value: "" };
}

export const ComprehensiveDataRequest_ConfigurationMapEntry: MessageFns<
  ComprehensiveDataRequest_ConfigurationMapEntry
> = {
  encode(
    message: ComprehensiveDataRequest_ConfigurationMapEntry,
    writer: BinaryWriter = new BinaryWriter(),
  ): BinaryWriter {
    if (message.key !== "") {
      writer.uint32(10).string(message.key);
    }
    if (message.value !== "") {
      writer.uint32(18).string(message.value);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ComprehensiveDataRequest_ConfigurationMapEntry {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseComprehensiveDataRequest_ConfigurationMapEntry();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.key = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.value = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ComprehensiveDataRequest_ConfigurationMapEntry {
    return {
      key: isSet(object.key) ? globalThis.String(object.key) : "",
      value: isSet(object.value) ? globalThis.String(object.value) : "",
    };
  },

  toJSON(message: ComprehensiveDataRequest_ConfigurationMapEntry): unknown {
    const obj: any = {};
    if (message.key !== "") {
      obj.key = message.key;
    }
    if (message.value !== "") {
      obj.value = message.value;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ComprehensiveDataRequest_ConfigurationMapEntry>, I>>(
    base?: I,
  ): ComprehensiveDataRequest_ConfigurationMapEntry {
    return ComprehensiveDataRequest_ConfigurationMapEntry.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ComprehensiveDataRequest_ConfigurationMapEntry>, I>>(
    object: I,
  ): ComprehensiveDataRequest_ConfigurationMapEntry {
    const message = createBaseComprehensiveDataRequest_ConfigurationMapEntry();
    message.key = object.key ?? "";
    message.value = object.value ?? "";
    return message;
  },
};

function createBaseMasterResponse(): MasterResponse {
  return { processingSuccess: false, summaryLog: "" };
}

export const MasterResponse: MessageFns<MasterResponse> = {
  encode(message: MasterResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.processingSuccess !== false) {
      writer.uint32(8).bool(message.processingSuccess);
    }
    if (message.summaryLog !== "") {
      writer.uint32(18).string(message.summaryLog);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MasterResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMasterResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.processingSuccess = reader.bool();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.summaryLog = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MasterResponse {
    return {
      processingSuccess: isSet(object.processingSuccess) ? globalThis.Boolean(object.processingSuccess) : false,
      summaryLog: isSet(object.summaryLog) ? globalThis.String(object.summaryLog) : "",
    };
  },

  toJSON(message: MasterResponse): unknown {
    const obj: any = {};
    if (message.processingSuccess !== false) {
      obj.processingSuccess = message.processingSuccess;
    }
    if (message.summaryLog !== "") {
      obj.summaryLog = message.summaryLog;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MasterResponse>, I>>(base?: I): MasterResponse {
    return MasterResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MasterResponse>, I>>(object: I): MasterResponse {
    const message = createBaseMasterResponse();
    message.processingSuccess = object.processingSuccess ?? false;
    message.summaryLog = object.summaryLog ?? "";
    return message;
  },
};

export type MasterServiceService = typeof MasterServiceService;
export const MasterServiceService = {
  submitComprehensiveData: {
    path: "/MasterPackage.MasterService/SubmitComprehensiveData" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: ComprehensiveDataRequest): Buffer =>
      Buffer.from(ComprehensiveDataRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): ComprehensiveDataRequest => ComprehensiveDataRequest.decode(value),
    responseSerialize: (value: MasterResponse): Buffer => Buffer.from(MasterResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): MasterResponse => MasterResponse.decode(value),
  },
} as const;

export interface MasterServiceServer extends UntypedServiceImplementation {
  submitComprehensiveData: handleUnaryCall<ComprehensiveDataRequest, MasterResponse>;
}

export interface MasterServiceClient extends Client {
  submitComprehensiveData(
    request: ComprehensiveDataRequest,
    callback: (error: ServiceError | null, response: MasterResponse) => void,
  ): ClientUnaryCall;
  submitComprehensiveData(
    request: ComprehensiveDataRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: MasterResponse) => void,
  ): ClientUnaryCall;
  submitComprehensiveData(
    request: ComprehensiveDataRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: MasterResponse) => void,
  ): ClientUnaryCall;
}

export const MasterServiceClient = makeGenericClientConstructor(
  MasterServiceService,
  "MasterPackage.MasterService",
) as unknown as {
  new (address: string, credentials: ChannelCredentials, options?: Partial<ClientOptions>): MasterServiceClient;
  service: typeof MasterServiceService;
  serviceName: string;
};

function bytesFromBase64(b64: string): Uint8Array {
  if ((globalThis as any).Buffer) {
    return Uint8Array.from((globalThis as any).Buffer.from(b64, "base64"));
  } else {
    const bin = globalThis.atob(b64);
    const arr = new Uint8Array(bin.length);
    for (let i = 0; i < bin.length; ++i) {
      arr[i] = bin.charCodeAt(i);
    }
    return arr;
  }
}

function base64FromBytes(arr: Uint8Array): string {
  if ((globalThis as any).Buffer) {
    return (globalThis as any).Buffer.from(arr).toString("base64");
  } else {
    const bin: string[] = [];
    arr.forEach((byte) => {
      bin.push(globalThis.String.fromCharCode(byte));
    });
    return globalThis.btoa(bin.join(""));
  }
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

function isObject(value: any): boolean {
  return typeof value === "object" && value !== null;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
