// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               v7.35.0
// source: user.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import {
  type CallOptions,
  type ChannelCredentials,
  Client,
  type ClientDuplexStream,
  type ClientOptions,
  type handleBidiStreamingCall,
  makeGenericClientConstructor,
  type Metadata,
  type UntypedServiceImplementation,
} from "@grpc/grpc-js";

export const protobufPackage = "UserPackage";

/** 1. Structure of an individual message packet */
export interface ChatMessage {
  sender: string;
  message: string;
}

function createBaseChatMessage(): ChatMessage {
  return { sender: "", message: "" };
}

export const ChatMessage: MessageFns<ChatMessage> = {
  encode(message: ChatMessage, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.sender !== "") {
      writer.uint32(10).string(message.sender);
    }
    if (message.message !== "") {
      writer.uint32(18).string(message.message);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ChatMessage {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseChatMessage();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.sender = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.message = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ChatMessage {
    return {
      sender: isSet(object.sender) ? globalThis.String(object.sender) : "",
      message: isSet(object.message) ? globalThis.String(object.message) : "",
    };
  },

  toJSON(message: ChatMessage): unknown {
    const obj: any = {};
    if (message.sender !== "") {
      obj.sender = message.sender;
    }
    if (message.message !== "") {
      obj.message = message.message;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ChatMessage>, I>>(base?: I): ChatMessage {
    return ChatMessage.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ChatMessage>, I>>(object: I): ChatMessage {
    const message = createBaseChatMessage();
    message.sender = object.sender ?? "";
    message.message = object.message ?? "";
    return message;
  },
};

export type UserServiceService = typeof UserServiceService;
export const UserServiceService = {
  /** 2. Placing 'stream' on BOTH input and output activates full-duplex bidirectional streaming */
  liveCoachChat: {
    path: "/UserPackage.UserService/LiveCoachChat" as const,
    requestStream: true as const,
    responseStream: true as const,
    requestSerialize: (value: ChatMessage): Buffer => Buffer.from(ChatMessage.encode(value).finish()),
    requestDeserialize: (value: Buffer): ChatMessage => ChatMessage.decode(value),
    responseSerialize: (value: ChatMessage): Buffer => Buffer.from(ChatMessage.encode(value).finish()),
    responseDeserialize: (value: Buffer): ChatMessage => ChatMessage.decode(value),
  },
} as const;

export interface UserServiceServer extends UntypedServiceImplementation {
  /** 2. Placing 'stream' on BOTH input and output activates full-duplex bidirectional streaming */
  liveCoachChat: handleBidiStreamingCall<ChatMessage, ChatMessage>;
}

export interface UserServiceClient extends Client {
  /** 2. Placing 'stream' on BOTH input and output activates full-duplex bidirectional streaming */
  liveCoachChat(): ClientDuplexStream<ChatMessage, ChatMessage>;
  liveCoachChat(options: Partial<CallOptions>): ClientDuplexStream<ChatMessage, ChatMessage>;
  liveCoachChat(metadata: Metadata, options?: Partial<CallOptions>): ClientDuplexStream<ChatMessage, ChatMessage>;
}

export const UserServiceClient = makeGenericClientConstructor(
  UserServiceService,
  "UserPackage.UserService",
) as unknown as {
  new (address: string, credentials: ChannelCredentials, options?: Partial<ClientOptions>): UserServiceClient;
  service: typeof UserServiceService;
  serviceName: string;
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
